### ISSUE TITLE
Trade Companion improvements

### ISSUE THREAD

**Issue by fatings** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#227]
Hello,

Quick note, great job on the trade companion, I was thinking of going trade trade league, this came just in time. Thanks.

My feedback on the feature:

1.  Add an option to allow to auto-hide the overlay when there's no trade active. Avoids the following issue:
![image](https://user-images.githubusercontent.com/39002567/126032090-91f7cb42-799d-43dc-9529-3e1474d11754.png)

2. Add an option to right-align the whole UI (this kinda gets deprecated by feedback number 1, because it seems to only be a problem when visible without any trade
3. Add an option to auto-minimize every trade request (automatically, when added)
4. Add an option to auto-minimize every trade except for the last one (automatically, when a new one is added minimize the previous one)
5. Allow to bind keys to actions to allow quick actions on the last trade (this goes well with feedback number 4, so you'll always know which trade is active).
6. Add an option for outgoing trades (buying) to go to your hideout or just add a custom field in trade actions for custom commands

Thanks again on the development.

Best regards.

**Comment by WhiteFang5** [comment]
Great suggestions! We'll look into them and see which ones can be added. I especially like number 4 combined with 5. I have been contemplating on how I could go about adding short-cuts for certain trade actions/buttons, but held back because I couldn't think of a good way on how to deal with multiple trades.  
  
Some further thoughts that came to mind reading the above suggestions:
1. Make auto-minimize work with the following options (maybe separate incoming & outgoing?):
* Always Minimize incoming trades
* Minimize previous trade on new incoming trade (unless the max. visibility is reached, then the last visible one stays visible instead of minimizing itself with the next trade not showing up due to the visible limit set in the settings)
* Minimize new trades (i.e. keeping the first trade the "active" trade)
  
2. Also added optional key-binds to make the next/previous trade the active one; and add an option to collapse the "previously active" trade
  
3. Add an optional border color around the "active trade" to properly indicate which trade options will be used (i.e. to whom you're sending messages) when using a shortcut key.
  
4. Regarding your 6th suggestion: It was intended to add a "home" button to the companion bar, but didn't end up doing so because you can already set it as a short-cut (default is F5) so I thought it would be redundant. But apparently people want a dedicated button for it, so we can add one to the bar.

**Comment by fatings** [comment]
Thanks for your feedback, just a quick comment regarding my number 6 and your number 4:
My suggestion isn't to add a new button to the trade bar, but to add a new option inside the trade option:
![image](https://user-images.githubusercontent.com/39002567/126211105-b852dc60-527a-4abd-94dd-15823de9b8da.png)

Adding here a new checkbox "Go to hideout" or if you want it more flexible, just add a textbox with "Custom command" where people can type, for instance, /hideout:

Quick MS Paint visualization:
![image](https://user-images.githubusercontent.com/39002567/126211670-ff052cc5-a9f6-4bc7-adde-baa1ddb86fa0.png)


Thanks for all your work.

Best regards.

**Comment by WhiteFang5** [comment]
I'm not sure if I fully understand what you're hinting at in your last reply, so I'm going to assume some stuff.  
If the intention is to have a "thx" button which sends the thx message to the player, and then also (instantly) teleports you to your hideout, then this isn't allowed. Sending a whisper is one server-command, going to your HO (i.e. sending "/hideout") is another command; and sending more than one command per button/shortcut press is not allowed by GGG's ToS for tools (such as poe overlay CF).  
So if you want to return to your HO after clicking the "thx" button, you can use/create a command shortcut (in the "commands" tab of the settings menu) to go to your HO (the default shortcut for this is F5).  
On top of that, I've also added a "home" or "HO" button to the trade notification panel for easy access (in case you don't like shortcut keys and prefer a button instead)

**Comment by WhiteFang5** [comment]
The majority of the mentioned improvements have been added in #231 and will be available in the next release.
