### ISSUE TITLE
Price checking breaks chrome on second monitor

### ISSUE THREAD

**Issue by CedricDixon** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#253]
When I price check an item my youtube window on my second monitor will go pure white and I have to scroll the page to fix this. Only started after I updated to the newest version.

**Comment by midgreezy** [comment]
Sort of the same issue here. When price/map checking any video (only tested chrome) on second monitor turns black. Clicking the video returns it to normal

**Comment by WhiteFang5** [comment]
This is due to Hardware Acceleration. Only one app can use it. Since your browser needs it to render the video, and poe overlay also likes to use it, it has to choose one of them and blackout the other. So when actively using poe overlay, your video/second monitor browser window will be "blacked out".  
  
And easy "fix", is to simply disable hardware acceleration for poe overlay by right-clicking the tray icon, and un-checking "hardware acceleration"
