### ISSUE TITLE
Unable to Leave Parties After Trade

### ISSUE THREAD

**Issue by mcshi** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#263]
Hi, I am currently unable to leave a party after a trade. The error that pops up is "settings.trade-companion.error.select-active-character". I'm not sure how to fix this, since there doesn't appear to be an option in settings where I can select an active character.

**Comment by WhiteFang5** [comment]
Hi, in order to "leave" a party, the app has to know your current character name. Since the app has no way of knowing this information on its own, and it can't be derived from trade/chat logs either, the solution is to allow users to select their active character.  
To make that process easier, you can simply login (the button can be found in the settings menu's "general" tab; carefully follow instruction to login written below the button) and select their currently active character (or allow it to be auto-selected).

**Comment by melink14** [comment]
Instead of opening a new issue I'll commetn here first with two thoughts:
1. Logging in is pretty heavy handed, is it possible to just have a text field where we can type our character name?
2. Should we update the documentation with this information? Currently there's a section in the README about what features logging in enables but it doesn't mention this. It also makes sense that in the settings tab we could surface a warning that certain buttons won't work due to not being logged in.
