### ISSUE TITLE
Evaluate item no longer works

### ISSUE THREAD

**Issue by thatguy692** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#274]
# 🐞 bug report

Ctrl + D doesn't work anymore, says **"An error occured while parsing the item"**
Windowed fullscreen

## 🌍  Your Environment

- OS:  e.g. Win10 x64
- Version:  e.g. 0.8.10 portable

**Comment by WhiteFang5** [comment]
Can you confirm you've selected a league in the General Settings?  
Without a league selected, this error might occur.

**Comment by eusoc** [comment]
Same problem, league is selected

**Comment by ParogDev** [comment]
@thatguy692 I came here after experiencing the same thing. I want to help you fix this, as this project going to Overwolf was one of the reasons why I quit PoE. Here's some info;

```MarkDown
- Windows 10
- Vulkan renderer
- PoE ran as a normal user
- Used the installation method for PoE-Overlay-Community
- Logged in, language and league selected, current character detected
```

PoE-Overlay-Community does not copy the item info to clipboard, this is what is causing the issue above, amongst others that rely on this mechanic.

I tested this by trying to open a wiki ( `alt + w` ) to an item, and was told the same thing as the users above. I then pressed CTRL+C on the item, and saw that it successfully copied it this time. Doing `alt + w` on any item would open the old one I had copied manually.

I tried restarting PoE-Overlay-Community as admin, and it worked just fine. However, this is not a workaround. Admin access shouldn't be required for clipboard access. Hope this points you in the right direction. ;) I might give you a hand once I see how you fix this one in the commits.

**Comment by thatguy692** [comment]
It is true that when i Ctrl+C and then Ctrl+D its working properly.

**Comment by ParogDev** [comment]
I actually meant to tag a dev, not you. Nice find on the "Use advanced copy mods" option!

**Comment by WhiteFang5** [comment]
> It is true that when i Ctrl+C and then Ctrl+D its working properly.
> 
> EDIT: it seems that the culprit is the "Use advanced copy mods" option, when i disable it it works fine again.

That is indeed a new feature that got added. Can you check your in-game options and see if you have "advanced mod descriptions" enabled or disabled?
![image](https://user-images.githubusercontent.com/4527188/152943108-aaf3cf8e-8eba-471f-99f7-a9901ef419c9.png)
I believe for the "Use advanced copy mods" to work, you need to have it enabled in-game.  
  
When it is toggled on as a setting in PoE Overlay CF, it'll use CTRL+ALT+C to make an advanced mod copy of your item (instead of a regular copy that's done using CTRL+C)

**Comment by ParogDev** [comment]
> @ParogDev The wiki (ALT+W) not working is probably related to this too, since the item has to be copied & parsed first for the wiki module to then use the item's name to open up the correct wiki page. Thus when parsing fails, the wiki page can't be opened up either.

@WhiteFang5 My issue should be a separate issue, so what I said might not apply here. Something failed yesterday, and even Awakened Poe Trade Community couldn't send inputs to the game window. I restarted today and everything works A1 on my end.

I looked into the modules that you wrote for it. Good work by the way. I'm fairly sure in my case it couldn't get focus on the window to send the copy command. 


> [Edit] It might be that I'm wrong about this though 🤔 ... I've disabled the advanced mods descriptions in-game, and my CTRL+D (and ALT+W) still worked just fine. It is seems very odd that changing the "use advanced copy mods" setting fixes this issue 🤔

I tried this last night and it did not solve the issue for me, although my issue was different and most likely because of an error in my environment, of maybe it was just a first install bug. I did install a few things last night.


> [Edit 2] I'm also wondering which items you guys were trying to evaluate? Perhaps you can copy-paste them here (using CTRL+C ; or event CTRL+ALT+C) so I can check if it might simply be a "broken item", or check if it's more of a global issue.

With 
![image](https://user-images.githubusercontent.com/14525894/153075497-6a885040-1d65-4d11-aa12-e0016becd3b8.png)
and enabled in the interface settings as well.

CTRL+C:
```
Item Class: Stackable Currency
Rarity: Currency
Chaos Orb
--------
Stack Size: 10/10
--------
Reforges a rare item with new random modifiers
--------
Right click this item then left click a rare item to apply it.
Shift click to unstack.
```

CTRL+ALT+C
```
Item Class: Stackable Currency
Rarity: Currency
Chaos Orb
--------
Stack Size: 10/10
--------
Right click this item then left click a rare item to apply it.
Shift click to unstack.
```

@thatguy692 Could you try running the overlay as admin and try to see if you still have the same issue? I'm curious. Humor me please. 

Thanks for your work again and sorry about the confusion, I'm not having any issues anymore!

**Comment by eusoc** [comment]
> > It is true that when i Ctrl+C and then Ctrl+D its working properly.
> > EDIT: it seems that the culprit is the "Use advanced copy mods" option, when i disable it it works fine again.
> 
> That is indeed a new feature that got added. Can you check your in-game options and see if you have "advanced mod descriptions" enabled or disabled?

> When it is toggled on as a setting in PoE Overlay CF, it'll use CTRL+ALT+C to make an advanced mod copy of your item (instead of a regular copy that's done using CTRL+C), so I'm guessing if advanced mods is disabled in-game, this advanced copy simply doesn't work accordingly.

For me it was just an unlucky hotkey combination, because I set this with autohotkey... (no "~" on my keyboard)

![image](https://user-images.githubusercontent.com/63907069/153077343-1195eb98-3680-4e7d-8894-5dbde2d6fccd.png)

I changed it to a different combination and now it all work fine

**Comment by WhiteFang5** [comment]
Based on replies it looks like each one of you had their issues solved. Thanks for the replies and additional info. As far as I can see now, it looks like 0.8.10 functions fine (have been using it myself obviously).  
  
If anything new pops up, feel free to open a new ticket.
