### ISSUE TITLE
not working in Korean by Korean Client (Kakao)

### ISSUE THREAD

**Issue by MissaSolemnis** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#288]
# 🐞 bug report

**Describe the bug**
As you may know, most Koreans enjoy POE through Kakao Client, not GGG's client.
I don't know if that's the cause of the problem, but when I set the language to Korean through the Kakao Client, no matter how well I select the proper league(sentinel) and save the league in the settings, it doesn't work(not saved and void league setting).

Also, when searching for a price, "Item can not be parsed" is displayed and the price searching does not work without pop-up window either.
As far as I remember, it worked fine in version 0.7, but since version 0.8, this problem has been appearing.
If you solves this problem, I think it will become a price search program that many Korean users love.

**To Reproduce**

**Expected behavior**

**Screenshots**

## 🌍  Your Environment

- OS:  Win10 x64
- Version:  0.8.16 setup
- PoE:  Kakao 3.18.0b / Korean

**Comment by danfunga** [comment]
I am also a Korean user.
The same parsing error occurs.
Both the portable version and the installation version occur the same.
F5 key light works by executing with administrator privileges.

The pop-up doesn't pop up well when the trade whisper arrives, so can I see this as a matter of the same context?

**Comment by WhiteFang5** [comment]
>I don't know if that's the cause of the problem, but when I set the language to Korean through the Kakao Client, no matter how well I select the proper league(sentinel) and save the league in the settings, it doesn't work(not saved and void league setting).
You should also update the "Language" to Korean in the "game settings" section of the poe overlay settings window
![image](https://user-images.githubusercontent.com/4527188/169711731-1fc9f7e6-08da-4233-a0fe-87d52f089178.png)
Otherwise it will give errors like "Item can not be parsed"

**Comment by maeng4317** [comment]
My case is a little different, I'm a Korean user but I don't use Kakao. 
So I have to set up English so that I can recognize my account in Game Settings of overlay.
However, the overlay only works when the in-game language is in English and does not work with the message "Item can not be parsed" when it is in Korean.

**Comment by WhiteFang5** [comment]
@maeng4317 for your specific case a new setting was added "website language", which can be different from the "game language". This should allow you to login trough GGG's website (instead of Kakao; by using English as language), yet have the game in Korean and the game language set to Korean in poe overlay community fork.  
  
Regarding the other issues of not being able to parse items, please check if it still happens with a newer version of the app. If it does, please let us know so we can look into it again.
