### ISSUE TITLE
Videos on 2nd monitor go black when using PoE overlay

### ISSUE THREAD

**Issue by TactfulRanger** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#335]
Whenever I use the PoE Overlay, videos on my 2nd monitor go black. Happens with Twitch as well as Youtube.

I tried playing PoE without the overlay and then it doesn't happen.

Videos almost go immediately black when opening the PoE overlay settings.

## 🌍  Your Environment

- OS:  Win11 x64
- Version:  Latest

**Comment by WhiteFang5** [comment]
This black video stuff is a known issue with dual monitors. Both the App and your browser have hardware acceleration turned on (which is a good thing, don't get me wrong here), but for dual monitors it's not so useful since only one render source at a time. You can turn off hardware acceleration for poe overlay by right-clicking the tray icon and disabling it; that will fix the issue and allow the video to play normally while losing a tiny bit of performance in poe overlay's rendering (but not so bad that it causes lagg or anything like that)
