### ISSUE TITLE
Vendor recipes not working, window bounds set to 0

### ISSUE THREAD

**Issue by NoxVentus** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#340]
# 🐞 bug report

**Describe the bug**
 

Vendor recipe not working because trade overlay is stuck at "unset" or (0,0)

**To Reproduce**

1. Install poe
2. Run in administrator per the guide
3. Link account and select character and league.
4. Turn on Vendor recipes
**Expected behavior**

The vendor recipes should be pulling from my stash tabs to tell me what I need (and I think my inventory)
**Screenshots**

![image](https://github.com/PoE-Overlay-Community/PoE-Overlay-Community-Fork/assets/57207502/bf186c68-9474-405b-a22f-3c37539d933d)
![image](https://github.com/PoE-Overlay-Community/PoE-Overlay-Community-Fork/assets/57207502/fa49cb1f-7c00-4ea9-8856-94ca96184427)
![image](https://github.com/PoE-Overlay-Community/PoE-Overlay-Community-Fork/assets/57207502/1cd9ac22-3f81-4a6a-8739-9db04eb260b9)
![image](https://github.com/PoE-Overlay-Community/PoE-Overlay-Community-Fork/assets/57207502/57a84b65-d9e7-4069-9de1-00ba59c2e917)
![image](https://github.com/PoE-Overlay-Community/PoE-Overlay-Community-Fork/assets/57207502/2e66baf4-b4d1-4214-b6ec-fbf64f84f5b1)

## 🌍  Your Environment

- OS:  OS Name	Microsoft Windows 10 Home

- Version:  Version	10.0.19045 Build 19045

- PoE:  e.g. Steam 3.22.0/b English

**Comment by WhiteFang5** [comment]
Hi, to have a better understanding of the issue, can you provide a screenshot of the expanded chaos orb recipe settings?  
  
Without the settings, I would just be guessing what the problem might be. Based on the screenshots that have been provided, it looks like you're vendoring identified rare items with at least one item being item level 60~74. When the default settings are being used, the vendor recipe expects unidentified items in your stash tabs, thus will ignore identified items (this behaviour can be changed, that's why I'm interested in the detailed settings to see if there is a bug or rather a misconfiguration of expected behaviour.).

**Comment by NoxVentus** [comment]
Thank you for the response. I had wondered if it might be because they were identified so I filled my stash but I still get 0 as a result up there.
![image](https://github.com/PoE-Overlay-Community/PoE-Overlay-Community-Fork/assets/57207502/c3d8a10c-9c3b-4d14-935f-574d4330a47e)
![image](https://github.com/PoE-Overlay-Community/PoE-Overlay-Community-Fork/assets/57207502/c1686a5c-d016-48ec-a2fe-51c1b6b6762f)
I didn't change the chaos orb recipe it came with just for reference. Please let me know if you need any other info!

**Comment by WhiteFang5** [comment]
@NoxVentus thank you for the detailed screenshot and the stash tab. Both do help out to figure out the issue here.  
In the the settings you have the `stash tab search mode` set to `prefix` with the `stash tab search value` set to `Ch`, this means the app is looking through your stashes that have their name start with the letters `Ch`. Based on your screenshot, your tab is called `Dump`, so it seems like the app won't search that specific tab for chaos items. I'd would suggest changing either the stash tab name or the settings and see if that resolves the issue for you.

**Comment by NoxVentus** [comment]
Ah I see the problem was that I didn't know how it worked. I had no idea I had to set it this way or rename the tab to the default ch it came with. Thank you very much! That same tab is now read this way
![image](https://github.com/PoE-Overlay-Community/PoE-Overlay-Community-Fork/assets/57207502/53b8287e-cdf0-423d-a0b9-b7611c99aa48)

**Comment by WhiteFang5** [comment]
No problem. I didn't make any kind of manual on how to use it, so I understand that it might not be intuitive for everyone.  
if you have any more questions, feel free to ask them here on in our discord.
