### ISSUE TITLE
Remove Pricing Method Tagging option

### ISSUE THREAD

**Issue by wratho** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#40]
# 🐞 bug report

**Describe the bug**
The Tagging method is again GGG ToS

**To Reproduce**
Navigate Setting -> Evaluate -> Pricing Method and switch to Tagging
Price and item in your stash (in game) and click a result from a price check. This will auto tag your item.

**Expected behavior**
This Setting should not longer be enabled

**Comment by DmytroKanivets** [comment]
Why do you consider this against ToS, is there any comment from GGG regarding this feature?

As per their rule of thumb, "one click per one server action", this is ok, as only server action executed here is setting a label to the item.

**Comment by kifers** [comment]
As far as I understand it, the overlay is fine as long as it can run without the game running.  In this case, the feature was specifically trying to interact with the game client by clicking various areas of the screen and pressing key binds to paste in a price.  This might work generally without the game client running (the clicks and key presses), but it doesn't serve the same purpose.  I'd argue for safety's sake to remove the feature since it seems like it's on the edge of what's acceptable.

**Comment by DmytroKanivets** [comment]
Logout/Hideout macro are doing the same - interacting with game client directly, and they are allowed. IMHO, previously it was better - to have the feature present, but disabled by default.
