### ISSUE TITLE
Suggestion: Price Check Inside Divination Stash Tab

### ISSUE THREAD

**Issue by donq123** [PoE-Overlay-Community/PoE-Overlay-Community-Fork#92]
If I was to try to check an card (ctrl+d) inside a divination tab i get, An error occurred while parsing the item.

**Comment by HiveSolution** [comment]
Problem with that is more on GGG.
CTRL+C in div tab does not return the item info, so it's not able to parse the item.
There's sadly no way to grab the item info from the div card tab at the moment.

**Comment by donq123** [comment]
Reason i requested is because the AHK trade-macro has this feature. I don't know how they implemented it though.

**Comment by WhiteFang5** [comment]
It used to work in the AHK trade-macro. I've found an old thread about it. In the end it was closed because it cannot be fixed. GGG changed the div stash tab to no longer copy the item data when pressing CTRL+C while hovering a div card there.

(Thread for reference: https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/673)

**Comment by wratho** [comment]
If this feature request cannot be resolved, should we close this?

**Comment by WhiteFang5** [comment]
> If this feature request cannot be resolved, should we close this?

Yes.

**Comment by wratho** [comment]
closing this request
